### ISSUE TITLE
Amino Acid Sequence Information

### ISSUE THREAD

**Issue by pthieringer** [NickJD/StORF-Reporter#3]
Hello! Thanks for making such helpful and exciting tool!

I am interested in trying to gain the amino acid sequences for my StORFs, but am having trouble understanding the correct way to produce this output. I was attempting to use the `-aa` flag to produce the sequences, however, I do not see any additional files or sequences within the .gff file that is being produced. Below is how I am running the tool:

`StORF-Reporter -anno Feature_Types Multiple_Genomes -p MARINE_MAGS -aa True`

The path contains the fast files and gff files for each MAG of interest. Any help or advice for what I may be missing for how to fix this step would be greatly appreciated! Hopefully there is just some piece of the puzzle I am missing?

**Comment by NickJD** [comment]
Hi. Thanks for reporting this. I think this feature may have been broken in a previous update. I will look into this and hopefully get a fix out early next week.

**Comment by NickJD** [comment]
Hi @pthieringer. I have pushed a new version today (v.1.1.2) to pip. Please could you try the workflow again and report back.
I will wait for a response before closing the issue.
Thanks!

**Comment by NickJD** [comment]
Make sure to add '-sout True' as that is the parameter to output StORFs into a separate .fasta file which the '-aa True' parameter is used to output those StORFs in amino acid form.

**Comment by pthieringer** [comment]
Awesome, thanks so much for the update! And I just re-installed and re-ran the code and was able to get the amino acid sequence files. Thanks so much for being on top of this and for your help!

**Comment by NickJD** [comment]
Fantastic!
I aim to continue updating the tool with requested features (some of my own ideas too) and also fix any bugs when reported! So thanks for bringing this to my attention and for quickly confirming the fixes work :)
